---
default: &defaults
  name: "Decidim Sant Cugat"
  # Supports ERB
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  ignore_errors:
    - SystemExit
    - ActionController::InvalidCrossOriginRequest
    - ActionController::RoutingError
    - ActionController::UnknownFormat
    - ActiveStorage::FileNotFoundError
  enable_frontend_error_catching: true
  enable_gc_instrumentation: true
  ignore_actions:
    - "Decidim::LinksController#new"
    - "ActiveStorage::BlobsController#show"
    - "ActiveStorage::RepresentationsController#show"

development:
  <<: *defaults
  active: true

test:
  <<: *defaults
  active: false

staging:
  <<: *defaults
  active: true

production:
  <<: *defaults
  active: true
